properties:
  title:
    type: string
    maxLength: 60
  description:
    type: string
    maxLength: 160
  keywords:
    type: array
    items:
      type: string
      enum:
        - API Mesh
        - App Builder
        - B2B
        - Backend Development
        - Cache
        - Checkout
        - Cloud
        - Configuration
        - Cron
        - Data Import
        - Data Export
        - Events
        - Extensibility
        - Extensions
        - GraphQL
        - Integration
        - Inventory
        - Merchandising
        - Payments
        - Performance
        - Personalization
        - Product discovery
        - Recommendations
        - Reporting
        - REST
        - Search
        - Security
        - Services
        - Storefront
        - Tools
        - Upgrade
        - Troubleshooting

required:
  - title
  - description
